### ISSUE TITLE
Add basic TinyMCE style for alignment

### ISSUE THREAD

**Issue by damien-pilot-in** [Pilot-in/PiloPress#80]
**Describe the bug**
It's not possible actually to center align an image in a wysiwyg.

**To Reproduce**
Add a media "image" and try to center align it.

**Expected behavior**
Default alignement should be here.

**Style to add by default**
```css
.aligncenter {
    display: block;
    margin-left: auto;
    margin-right: auto;
}

.alignleft {
    margin-left: auto;
    margin-right: 0;
}

.alignright {
    margin-left: 0;
    margin-right: auto;
}
```
